### ISSUE TITLE
hide back-to-top at top of page

### ISSUE THREAD

**Issue by marvinrusinek** [shivarajnaidu/ng-back-to-top#1]
Hello, I am using your library and it works fine, but I would like it to hide at the top of the page before the page scrolls. The reason I'm using your library is because I would like to use it with Server-Side Rendering with Angular Universal. Would you be able to make it work without using the DOM so that it works with Angular Universal? Please let me know. Thanks!

**Comment by shivarajnaidu** [comment]
Thanks for your interest @marvinrusinek  I'll do it, plans are there.. but due to busy schedule I can't make it immediately. 

Pull request will be helpful. Thank You !

**Comment by shivarajnaidu** [comment]
Hi @marvinrusinek , I think it's already hidden at the top right ?

**Comment by marvinrusinek** [comment]
Yes it seems to work on that website. I was trying to customize the button to use a chevron instead of the triangle using font-awesome but couldn't get it to remain hidden at the top with the code below. I guess I can use the code that you provided in the documentation.

<ng-back-to-top>
  <div class="fixed-back-to-top-btn-container">
    <button title="Scroll to top">
      <span class="fa fa-chevron-up"></span>
    </button>
  </div>
</ng-back-to-top>

.fa {
  padding: 12px 14px 14px;
  background-color: #016f86;
  color: #fff;
  font-size: 18px;
  line-height: 10px;
  cursor: pointer;
}

.fixed-back-to-top-btn-container {
   position: fixed;
   right: 0;
   bottom: 2rem;
   padding: 20px;
   cursor: pointer;
}

**Comment by shivarajnaidu** [comment]
still no o support for custom icons.. Soon I'll add it or pull request from you will be helpful to get it immediately  :blush:

**Comment by marvinrusinek** [comment]
I forked the repo but not sure how to do the pull request.

**Comment by shivarajnaidu** [comment]
Did you add the support for custom icons ?

**Comment by marvinrusinek** [comment]
I tried adding the pull request but wasn't able to figure it out how to do it.

**Comment by shivarajnaidu** [comment]
You can see the pull-request button at the top right corner 
![image](https://user-images.githubusercontent.com/12374494/51781159-f42e3700-213a-11e9-8092-e650ecee6e0e.png)  Click On It.. If you have updated code

**Comment by marvinrusinek** [comment]
Yes I tried clicking that button but don't know how to set up the pull
request. This is the only code I'm using:

<ng-back-to-top bgColor="#016f86" color="#fff"></ng-back-to-top>

**Comment by shivarajnaidu** [comment]
You just commit your changes in your repo / fork @marvinrusinek

**Comment by marvinrusinek** [comment]
I have committed the changes to my repo. Now what?

**Comment by shivarajnaidu** [comment]
I don't see any commits in your repo in github.. Could you please share a link...

**Comment by marvinrusinek** [comment]
https://github.com/marvinrusinek/portfolio/blob/master/src/app/app.component.html

**Comment by shivarajnaidu** [comment]
No worries.. I'll implement the feature.. Thank you !

**Comment by yuvarajvemula** [comment]
These feature covered as of release of 1.0.0
